# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gemspec

gem 'tramway-admin'
gem 'tramway-conference'
gem 'tramway-core'
gem 'tramway-landing'
gem 'tramway-news'
gem 'tramway-profiles'
gem 'tramway-sport_school'
