language: ruby
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
services:
  postgresql
before_script:
  - cd spec/dummy
  - RAILS_ENV=test bundle exec rails db:create db:migrate
  - cd ../../..
before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-9.5
  - cd tramway-core
  - gem install bundler -v '~> 2.0'
script:
  - make
