source 'https://rubygems.org'
gemspec
gem 'tramway-user', github: 'ulmic/tramway-user', branch: :develop
gem 'tramway-core', github: 'ulmic/tramway-core', branch: :develop
gem 'haml-rails'
gem 'sass-rails'
gem 'bootstrap', '~> 4.0.0.beta2.1'
gem 'audited'
gem 'simple_form'
gem 'bcrypt'
gem 'reform-rails'
gem 'font-awesome-rails'
gem 'trap', '~> 2.0'
gem 'copyright_mafa'
gem 'enumerize'
gem 'kaminari'
gem 'bootstrap-kaminari-views', github: 'kalashnikovisme/bootstrap-kaminari-views', branch: :master
gem 'state_machine_buttons'
gem 'loofah', '~> 2.2.1'

group :development do
  gem 'better_errors'
  gem 'pry'
  #gem 'tramway-user', path: '../tramway-user'
  #gem 'tramway-core', path: '../tramway-core'
end
