source 'https://rubygems.org'
gemspec
gem 'reform-rails'
gem 'simple_form'
gem 'sass-rails'
gem 'bootstrap', '~> 4.0.0.beta2.1'
gem 'audited'
gem 'disposable', github: 'apotonick/disposable'
gem 'enumerize'
gem 'mini_magick'
gem 'rmagick'
gem 'loofah', '~> 2.2.1'

group :development do
  gem 'better_errors'
end
